# https://github.com/dart-lang/setup-dart/blob/main/README.md
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_VERSION: "${{ github.sha }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build-binaries:
    name: "Build binaries"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Set BUILD_OS environment variable for Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo "BUILD_OS=linux" >> $GITHUB_ENV
      - name: Set BUILD_OS environment variable for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: echo "BUILD_OS=darwin" >> $GITHUB_ENV
      - name: Set BUILD_ARCH environment variable
        run: echo "BUILD_ARCH=amd64" >> $GITHUB_ENV

      - name: Create build folder
        run: mkdir -p build

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output build/git-lfs-authenticate
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output build/git-lfs-server
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server

  build-images:
    name: "Build images"
    needs:
      - build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set BUILD_OS environment variable for Linux
        run: echo "BUILD_OS=linux" >> $GITHUB_ENV
      - name: Set BUILD_ARCH environment variable
        run: echo "BUILD_ARCH=amd64" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate
      - uses: actions/download-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server
      - name: List binaries
        run: ls -la build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.actor }}/amz-git-mirroring:${{ env.BUILD_VERSION }}
