# https://github.com/dart-lang/setup-dart/blob/main/README.md
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Set SHORT_SHA environment variable
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Set BUILD_NUMBER environment variable
        run: echo "BUILD_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Set BUILD_OS environment variable for Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo "BUILD_OS=linux" >> $GITHUB_ENV

      - name: Set BUILD_OS environment variable for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: echo "BUILD_OS=darwin" >> $GITHUB_ENV

      - name: Set BUILD_ARCH environment variable
        run: echo "BUILD_ARCH=amd64" >> $GITHUB_ENV

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }}
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }}
          path: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }}

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }}
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }}
          path: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }}

      - name: Copy binaries to build folder
        run: mkdir -p build && cp git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }} build/git-lfs-authenticate && cp git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }} build/git-lfs-server

      - name: Login to Docker Hub
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring:${{ env.BUILD_NUMBER }}-${{ env.SHORT_SHA }}
      - name: Update repo description
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring
