name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-images:
    name: "Build images"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: echo "BUILD_VERSION=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/amz-git-mirroring:${{ env.BUILD_VERSION }}
            ghcr.io/${{ github.actor }}/amz-git-mirroring:latest
