name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_VERSION: "${{ github.sha }}::7"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build-binaries-macos-amd64:
    name: "Build binaries for macOS AMD64"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-latest]
        arch: [amd64]
    env:
      BUILD_OS: "macos"
      BUILD_ARCH: "${{ matrix.arch }}"
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Create build folder
        run: mkdir -p build

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output build/git-lfs-authenticate
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output build/git-lfs-server
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server

  build-binaries-linux-amd64:
    name: "Build binaries for Linux AMD64"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64]
    container:
      image:
        amd64/dart
      options: --tty --platform linux/${{ matrix.arch }}
    env:
      BUILD_OS: "linux"
      BUILD_ARCH: "${{ matrix.arch }}"
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
          architecture: x64

      - name: Install dependencies
        run: dart pub get

      - name: Create build folder
        run: mkdir -p build

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output build/git-lfs-authenticate
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output build/git-lfs-server
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server

  build-binaries-linux-arm64:
    name: "Build binaries for Linux ARM64"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]
    env:
      BUILD_OS: "linux"
      BUILD_ARCH: "${{ matrix.arch }}"
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Build ARM64 binaries
        with:
          arch: aarch64
          distro: ubuntu18.04
          setup: |
            mkdir -p "${PWD}/build"
          dockerRunArgs: |
            --volume "${PWD}/build:/build"
          env: |
            BUILD_BRANCH: "${{ github.head_ref }}"
          install: |
            apt-get update -q
            apt-get install -q -y curl git unzip
            curl --connect-timeout 15 --retry 5 "https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-linux-arm64-release.zip" > "${HOME}/dartsdk.zip"
            unzip -o "${HOME}/dartsdk.zip" -d "${HOME}" > /dev/null
            if [ $? -ne 0 ]; then
              echo -e "::error::Download failed! Please check passed arguments."
              exit 1
            fi
            rm "${HOME}/dartsdk.zip"
            PUBCACHE="${HOME}/.pub-cache"
            DART_HOME="${HOME}/dart-sdk"
            echo "PUB_CACHE=${PUBCACHE}" >> ${HOME}/.bashrc
            echo "Pub cache set to: ${PUBCACHE}"
            echo "DART_HOME=${DART_HOME}" >> ${HOME}/.bashrc
            echo -e "Successfully installed Dart SDK:"
            ${HOME}/dart-sdk/bin/dart --version
          run: |
            git clone --quiet https://github.com/khoa-io/git-lfs-server.git --branch "${BUILD_BRANCH}" --depth 1
            cd git-lfs-server
            "${HOME}/dart-sdk/bin/dart" pub get
            "${HOME}/dart-sdk/bin/dart" compile exe bin/git_lfs_server.dart --output git-lfs-server
            "${HOME}/dart-sdk/bin/dart" compile exe bin/git_lfs_authenticate.dart --output git-lfs-authenticate
            cp git-lfs-server "/build"
            cp git-lfs-authenticate "/build"
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server

  build-images:
    name: "Build images"
    needs:
      - build-binaries-linux-amd64
      - build-binaries-linux-arm64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      BUILD_OS: "linux"
      BUILD_ARCH: "${{ matrix.arch }}"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate
      - uses: actions/download-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server
      - name: List binaries
        run: ls -la build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ghcr.io/${{ github.actor }}/amz-git-mirroring:${{ env.BUILD_VERSION }}
