# https://github.com/dart-lang/setup-dart/blob/main/README.md
name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output git-lfs-authenticate-${{ matrix.os }}
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ matrix.os }}
          path: git-lfs-authenticate-${{ matrix.os }}

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output git-lfs-server-${{ matrix.os }}
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ matrix.os }}
          path: git-lfs-server-${{ matrix.os }}
