# https://github.com/dart-lang/setup-dart/blob/main/README.md
name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output git-lfs-authenticate-${{ matrix.os }}-${{ env.SHORT_SHA }}
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ matrix.os }}-${{ env.SHORT_SHA }}
          path: git-lfs-authenticate-${{ matrix.os }}-${{ env.SHORT_SHA }}

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output git-lfs-server-${{ matrix.os }}-${{ env.SHORT_SHA }}
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ matrix.os }}-${{ env.SHORT_SHA }}
          path: git-lfs-server-${{ matrix.os }}-${{ env.SHORT_SHA }}

      - name: Copy binaries to build folder
        run: mkdir -p build && cp git-lfs-authenticate-${{ matrix.os }}-${{ env.SHORT_SHA }} build/git-lfs-authenticate && cp git-lfs-server-${{ matrix.os }}-${{ env.SHORT_SHA }} build/git-lfs-server

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/khoa10/amz-git-mirroring:${{ env.SHORT_SHA }}
