name: Release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_VERSION: "${{ github.ref_name }}"

jobs:
  build-binaries-macos-amd64:
    name: "Build binaries for macOS AMD64"
    runs-on: macos-latest
    env:
      BUILD_OS: "macos"
      BUILD_ARCH: "amd64"
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Create build folder
        run: mkdir -p build

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output build/git-lfs-authenticate
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output build/git-lfs-server
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server

  build-binaries-linux-amd64:
    name: "Build binaries for Linux AMD64"
    runs-on: ubuntu-latest
    env:
      BUILD_OS: "linux"
      BUILD_ARCH: "amd64"
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Create build folder
        run: mkdir -p build

      - name: Build git-lfs-authenticate
        run: dart compile exe bin/git_lfs_authenticate.dart --output build/git-lfs-authenticate
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate

      - name: Build git-lfs-server
        run: dart compile exe bin/git_lfs_server.dart --output build/git-lfs-server
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server

  build-binaries-linux-arm64:
    name: "Build binaries for Linux ARM64"
    runs-on: ubuntu-latest
    env:
      BUILD_OS: "linux"
      BUILD_ARCH: "arm64"
    steps:
      - uses: actions/checkout@v3
      - name: Compute environment variables
        run: |
          echo "RUNNER_UID=`id -u`" >> $GITHUB_ENV
          echo "RUNNER_GID=`id -g`" >> $GITHUB_ENV

      # Run inside a linux/arm64 container
      - uses: uraimo/run-on-arch-action@v2
        name: Build ARM64 binaries
        with:
          arch: aarch64
          distro: ubuntu18.04
          setup: |
            mkdir -p "${PWD}/build"
            curl --connect-timeout 15 --retry 5 "https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-linux-arm64-release.zip" > "${HOME}/dartsdk.zip"
            unzip -o "${HOME}/dartsdk.zip" -d "${HOME}" > /dev/null
            if [ $? -ne 0 ]; then
              echo -e "::error::Download failed! Please check passed arguments."
              exit 1
            fi
          dockerRunArgs: |
            --volume "${PWD}:/source"
            --volume "${PWD}/build:/build"
            --volume "${HOME}/dart-sdk:/dart-sdk"
            --user "${{ env.RUNNER_UID }}:${{ env.RUNNER_GID }}"
          env: |
            PUB_CACHE: "${HOME}/.pub-cache"
            DART_HOME: "/dart-sdk"
          run: |
            cd /source
            ${DART_HOME}/bin/dart --version
            ${DART_HOME}/bin/dart pub get
            ${DART_HOME}/bin/dart compile exe bin/git_lfs_server.dart --output /build/git-lfs-server
            ${DART_HOME}/bin/dart compile exe bin/git_lfs_authenticate.dart --output /build/git-lfs-authenticate
      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate

      - uses: actions/upload-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server

  build-images:
    name: "Build images"
    needs:
      - build-binaries-linux-amd64
      - build-binaries-linux-arm64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      BUILD_OS: "linux"
      BUILD_ARCH: "${{ matrix.arch }}"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-authenticate
      - uses: actions/download-artifact@v3
        with:
          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
          path: build/git-lfs-server
      - name: List binaries
        run: ls -la build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring:${{ env.BUILD_VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring
